version: '2'

run:
  build-tags:
    - acceptance

issues:
  fix: true

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113 # TODO: turn on and fix
    - errorlint # TODO: turn on and fix
    - exhaustive
    - exhaustruct
    - godox
    - gomoddirectives # TODO: remove when go-rpm is updated.
    - mnd
    - musttag
    - nlreturn
    - nonamedreturns
    - paralleltest
    - recvcheck
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    gomodguard:
      blocked:
        modules:
          - encoding/json:
              recommendations: [github.com/goccy/go-json]
          - github.com/pkg/errors:
              recommendations: [errors]
    gosec:
      excludes:
        - G204
        - G401
        - G501
        - G505
    govet:
      disable:
        - fieldalignment
      enable-all: true
    ireturn:
      allow:
        - error
        - generic
        - stdlib
        - github.com/google/go-cmp/cmp.Option
        - github.com/kubri/kubri/target.Target
    nolintlint:
      require-specific: true
    tagalign:
      order:
        - yaml
        - validate
        - jsonschema
    tagliatelle:
      case:
        rules:
          deb: header
          yaml: kebab
        use-field-name: true
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - contextcheck
          - cyclop
          - errcheck
          - funlen
          - gocognit
          - goconst
          - gosec
          - lll
          - maintidx
        path: (.+)_test.go
      - linters: [govet]
        text: 'shadow: declaration of "err" shadows declaration'
      - linters: [staticcheck]
        text: 'SA1019: "crypto/dsa" has been deprecated'
      - linters: [lll]
        source: ^\s*//
      - linters: [revive]
        text: '^(exported|package-comments): .*$'

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes: [github.com/kubri/kubri]
