run:
  timeout: 5m
  build-tags:
    - acceptance
  skip-dirs:
    - testdata

linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    # - sql
    - style
    - test
    - unused
  disable:
    - cyclop
    - deadcode # deprecated
    - depguard
    - errorlint # TODO: turn on and fix
    - exhaustive
    - exhaustivestruct # deprecated
    - exhaustruct
    - gci
    - godox
    - goerr113 # TODO: turn on and fix
    - golint # deprecated
    - gomoddirectives # TODO: remove when go-rpm is updated.
    - gomnd
    - interfacer # deprecated
    - ireturn # false positive on returning generic
    - maligned # deprecated
    - musttag
    - nonamedreturns
    - nosnakecase # deprecated
    - nlreturn
    - paralleltest
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  gofmt:
    rewrite-rules:
      - pattern: interface{}
        replacement: any
  gofumpt:
    extra-rules: true
  gomodguard:
    blocked:
      modules:
        - encoding/json:
            recommendations:
              - github.com/goccy/go-json
        - github.com/pkg/errors:
            recommendations:
              - errors
  gosec:
    excludes:
      - G107
      - G204
      - G401
      - G501
      - G505
  govet:
    enable-all: true
    disable:
      - fieldalignment
  nolintlint:
    require-specific: true
  tagliatelle:
    case:
      use-field-name: true
      rules:
        yaml: kebab
        deb: header
  tagalign:
    order:
      - yaml
      - validate
      - jsonschema
issues:
  fix: true
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - cyclop
        - errcheck
        - funlen
        - gocognit
        - goconst
        - gosec
        - lll
        - maintidx
    - linters:
        - govet
      text: 'shadow: declaration of "err" shadows declaration'
    - linters:
        - staticcheck
      text: 'SA1019: "crypto/dsa" has been deprecated'
    - linters:
        - lll
      source: '^\s*//'
