builds:
  - main: ./cmd/appcast
    targets:
      - go_first_class

archives:
  - format: binary

checksum:
  disable: true

changelog:
  skip: true

brews:
  - tap:
      owner: abemedia
      name: homebrew-tap
    license: MIT
    test: system "#{bin}/appcast version"
    folder: Formula
    description: A CLI tool for signing update packages and creating appcast XML for use with Sparkle.
