version: 2

builds:
  - targets:
      - go_first_class
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0

universal_binaries:
  - replace: false

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}MacOS{{- else }}{{- title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE

nfpms:
  - id: packages
    file_name_template: '{{ .ConventionalFileName }}'
    homepage: https://github.com/kubri/kubri
    description: >-
      Kubri signs and releases software for common package managers and
      software update frameworks.
    maintainer: Adam Bouqdib <adam@abemedia.co.uk>
    license: MIT
    vendor: Kubri
    section: utils
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    contents:
      - src: build/linux/kubri.gpg
        dst: /usr/share/keyrings/kubri.gpg
        packager: deb
      - src: build/linux/kubri.list
        dst: /etc/apt/sources.list.d/kubri.list
        packager: deb
      - src: build/linux/kubri.repo
        dst: /etc/yum.repos.d/kubri.repo
        packager: rpm
      - src: LICENSE
        dst: /usr/share/doc/kubri/copyright

snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: Distribute auto-updating software with ease
    description: >-
      Kubri signs and releases software for common package managers and
      software update frameworks.
    grade: stable
    confinement: classic
    publish: true
    disable: true # TODO: enable

brews:
  - repository:
      owner: kubri
      name: homebrew-tap
    license: MIT
    test: system "#{bin}/kubri version"
    directory: Formula
    homepage: https://kubri.dev/
    description: >-
      Kubri signs and releases software for common package managers and
      software update frameworks.

winget:
  - name: Kubri
    publisher: Kubri
    short_description: Distribute auto-updating software with ease
    description: >-
      Kubri signs and releases software for common package managers and
      software update frameworks.
    license: MIT
    homepage: https://kubri.dev/
    publisher_url: https://kubri.dev/
    publisher_support_url: https://github.com/kubri/kubri/issues
    release_notes_url: https://github.com/kubri/kubri/releases/tag/{{.Tag}}
    tags:
      - release
      - update
      - devops
      - tool
      - repository
      - apt
      - yum
      - apk
      - sparkle
      - appinstaller
    repository:
      owner: kubri
      name: winget-pkgs
      branch: kubri-{{.Version}}
      pull_request:
        enabled: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

dockers:
  - image_templates:
      - kubri/kubri:v{{ .Version }}-amd64
    dockerfile: build/docker/Dockerfile
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.description=Sign and release software
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.url={{.GitURL}}
      - --label=org.opencontainers.image.documentation=https://kubri.dev/
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --platform=linux/amd64
  - image_templates:
      - kubri/kubri:v{{ .Version }}-arm64
    goos: linux
    goarch: arm64
    dockerfile: build/docker/Dockerfile
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.description=Sign and release software
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.url={{.GitURL}}
      - --label=org.opencontainers.image.documentation=https://kubri.dev/
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --platform=linux/arm64

docker_manifests:
  - name_template: kubri/kubri:v{{ .Version }}
    image_templates:
      - kubri/kubri:v{{ .Version }}-amd64
      - kubri/kubri:v{{ .Version }}-arm64
  - name_template: kubri/kubri:latest
    image_templates:
      - kubri/kubri:v{{ .Version }}-amd64
      - kubri/kubri:v{{ .Version }}-arm64

changelog:
  disable: true
