version: '>=0.6.0'

source:
  type: github
  owner: kubri
  repo: kubri

target:
  type: s3
  bucket: kubri-packages
  region: auto
  endpoint: https://44d8880eefdff4523e34b12529c6e1ed.r2.cloudflarestorage.com
  url: https://pkg.kubri.dev/

apk:
  folder: alpine
  key-name: info@kubri.dev

apt:
  folder: deb

arch:
  repo-name: kubri

yum:
  folder: rpm
