# https://taskfile.dev

version: '3'

env:
  CGO_ENABLED: '0'

dotenv:
  - .env

vars:
  GIT_COMMIT:
    sh: git log -n 1 --format="%h (%ci)"

tasks:
  default:
    desc: Runs the default tasks
    cmds:
      - task: init
      - task: mod
      - task: lint
      - task: test
      - task: build

  init:
    desc: Setup git hooks & dev dependencies
    cmds:
      - cp -f scripts/pre-commit.sh .git/hooks/pre-commit
      - test gotestsum || go install gotest.tools/gotestsum@latest

  mod:
    desc: Download Go modules
    cmds:
      - go mod tidy

  build:
    desc: Build the binary
    aliases: [b]
    sources:
      - ./**/*.go
      - ./go.{mod,sum}
    generates:
      - ./kubri
    cmds:
      - go build

  lint:
    desc: Run golangci-lint
    aliases: [l]
    sources:
      - './**/*.go'
      - ./go.{mod,sum}
      - .golangci.yml
    cmds:
      - golangci-lint run --fix

  test:
    desc: Run test suite
    aliases: [t]
    cmds:
      - gotestsum -- -cover ./...

  golden:
    desc: Update golden test files
    aliases: [g]
    env:
      UPDATE_GOLDEN: '1'
    cmds:
      - gotestsum -- -cover ./...

  acceptance:
    desc: Run acceptance tests
    aliases: [a]
    cmds:
      - gotestsum -- -tags acceptance -run ^TestAcceptance$ ./integrations/...

  install:
    desc: Install Kubri
    aliases: [i]
    sources:
      - './**/*.go'
      - ./go.{mod,sum}
    cmds:
      - go install -ldflags="-X 'main.version={{.GIT_COMMIT}}'"

  docs:
    desc: Run docs website
    aliases: [d]
    dir: website
    cmds:
      - yarn start
