# https://taskfile.dev

version: '3'

env:
  CGO_ENABLED: '0'

dotenv:
  - .env

vars:
  GIT_COMMIT:
    sh: git log -n 1 --format="%h (%ci)"

tasks:
  default:
    desc: Runs the default tasks
    cmds:
      - task: init
      - task: mod
      - task: build
      - task: lint
      - task: test

  init:
    desc: Setup git hooks
    cmds:
      - cp -f scripts/pre-commit.sh .git/hooks/pre-commit

  mod:
    desc: Download Go modules
    cmds:
      - go mod tidy

  build:
    desc: Build the binary
    aliases: [b]
    sources:
      - ./**/*.go
      - ./go.(mod|sum)
    generates:
      - ./appcast
    cmds:
      - go build

  lint:
    desc: Runs golangci-lint
    aliases: [l]
    sources:
      - './**/*.go'
      - ./go.(mod|sum)
      - .golangci.yml
    cmds:
      - golangci-lint run

  test:
    desc: Runs test suite
    aliases: [t]
    cmds:
      - go test -cover ./...

  install:
    desc: Install AppCast
    aliases: [i]
    sources:
      - './**/*.go'
      - ./go.(mod|sum)
    cmds:
      - go install -ldflags="-X 'main.version={{.GIT_COMMIT}}'"
