name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        with:
          release-type: go
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          bump-minor-pre-major: true
