name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
      GITLAB_TOKEN:
        required: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - run: go mod download

      - run: go test -v ./... -coverprofile=coverage.out
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - run: go mod download

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true
